[project]
name = "assetmanager"
description = ""
version = "1.0.0"
license = {file = "LICENSE"} 

Repository = "https://github.com/c0dezer019/AssetManager"
#  Used by Comfy Registry https://registry.comfy.org
Documentation = "https://github.com/c0dezer019/AssetManager/wiki"
"Bug Tracker" = "https://github.com/c0dezer019/AssetManager/issues"

[tool.comfy]
PublisherId = "c0dezer019"
DisplayName = "AssetManager"
Icon = ""
includes = [] 
