[project]
name = "genhistory"
description = "An advanced assets tab for easy management of assets. This add filtering and sorting, as well as persistence."
version = "1.0.0"
license = {file = "LICENSE"} 

[project.urls]
Repository = "https://github.com/c0dezer019/GenHistory"
#  Used by Comfy Registry https://registry.comfy.org
Documentation = "https://github.com/c0dezer019/GenHistory/wiki"
"Bug Tracker" = "https://github.com/c0dezer019/GenHistory/issues"

[tool.comfy]
PublisherId = "DefinitelyNotHuman"
DisplayName = "GenHistory"
Icon = ""
includes = [] 
